### ISSUE TITLE
command not found: cover-enforcer

### ISSUE THREAD

**Issue by Creepo** [crocodilestick/Calibre-Web-Automator#10]
Running "docker exec calibre-web-automated cover-enforcer -all" (I hope this is how it's done, as I'm new to docker) returns the error "command not found: cover enforcer".

**Comment by crocodilestick** [comment]
Hi @Creepo , no that's not quite right, first you use:

docker exec -it calibre-web-automated bash

To access the CWA container's command line and from there you can enter commands like:

cover-enforcer -all

Best of luck and hope you enjoy CWA!
