### ISSUE TITLE
Goodreads as metadata provider 

### ISSUE THREAD

**Issue by Creepo** [crocodilestick/Calibre-Web-Automator#11]
Would it be possible to add Goodreads as a metadata provider? Or add more metadata providers in general?

**Comment by crocodilestick** [comment]
Hi @Creepo , unfortunately Goodreads locked down their API back in 2020 so unfortunately that is no longer feasible.

**Comment by blampe** [comment]
@crocodilestick I recently built a GR metadata provider ([link](https://github.com/blampe/rreading-glasses)) and I think this might actually be feasible. 

If you point me towards your metadata plugin requirements I can look into it.

**Comment by crocodilestick** [comment]
Hi @blampe , that would be great! How are you getting around GR not handing out API keys anymore though? You can find details on adding metadata providers [here](https://github.com/janeczku/calibre-web/wiki/Developer's-corner#add-metadata-provider)

**Comment by townsmcp** [comment]
@blampe just wondering if you have made any progress on integrating this yet?

**Comment by Enissay** [comment]
@blampe Any update please <3
