### ISSUE TITLE
Cover not being added after fetching metadata 

### ISSUE THREAD

**Issue by Creepo** [crocodilestick/Calibre-Web-Automator#12]
Fetching metadata doesn't seem to fetch the cover as well? I don't know if this is intended behavior or not.

**Comment by crocodilestick** [comment]
Hi @Creepo , it definitely does after testing, are you sure you're pressing 'save' at the bottom after making your changes? Otherwise could you please send some screenshots or something so we can better understand the issue?

**Comment by Creepo** [comment]
I'm pressing save.

Here are the screenshot showing initial book saying "no cover found", then the metadata I chose, then that I saved the metadata but the cover is still not there. I tested this with other books as well.

![SmartSelect_20240725_175406_Brave](https://github.com/user-attachments/assets/2920b4c9-7a2a-4976-820c-54676c414bbb)
![SmartSelect_20240725_175425_Brave](https://github.com/user-attachments/assets/02deaea6-2a43-425b-b31f-077605072c44)
![SmartSelect_20240725_175441_Brave](https://github.com/user-attachments/assets/f9a7d9e8-20b4-48c6-b6c5-36ee37ba7b8c)

**Comment by crocodilestick** [comment]
Ah I believe you have a permissions problem! Try the following steps:

1. docker exec -it calibre-web-automated bash
2. chown -R abc:1000 /calibre-main/

Run those commands in that order and that should fix your problem :)

**Comment by Creepo** [comment]
> Ah I believe you have a permissions problem! Try the following steps:
> 
> 1. docker exec -it calibre-web-automated bash
> 2. chown -R abc:1000 /calibre-main/
> 
> Run those commands in that order and that should fix your problem :)

I just tried that. Same issue.

**Comment by jmarmstrong1207** [comment]
Try adding read/write permissions with chmod -R ug+rw /calibre-main/. I am able to change the metadata cover on my side

**Comment by Creepo** [comment]
> Try adding read/write permissions with `chmod -R ug+rw /calibre-main/`. I am able to change the metadata cover on my side

Tested that too but no success. I even completely wiped configs and all, and tried again but still same issue. Oh well

**Comment by crocodilestick** [comment]
Try changing the permissions of the folder you bound to /calibre-main, outside of the container

**Comment by crocodilestick** [comment]
I wouldn't wipe any configs, no one else has this issue so you just have some funky permissions somewhere on your system

**Comment by jmarmstrong1207** [comment]
> > Try adding read/write permissions with `chmod -R ug+rw /calibre-main/`. I am able to change the metadata cover on my side
> 
> Tested that too but no success. I even completely wiped configs and all, and tried again but still same issue. Oh well

If you can, could you provide the calibre-web logs? And also if you're able to, see if this problem persists with regular calibre-web

**Comment by Creepo** [comment]
> > > Try adding read/write permissions with `chmod -R ug+rw /calibre-main/`. I am able to change the metadata cover on my side
> > 
> > 
> > Tested that too but no success. I even completely wiped configs and all, and tried again but still same issue. Oh well
> 
> If you can, could you provide the calibre-web logs? And also if you're able to, see if this problem persists with regular calibre-web

What's the command for the logs?
1. I just gave full rw permission to the folder bound to calibre-main. No difference. 
2. I tested on the regular calibre-web. Same issue, first time testing that there actually. Did step 1 here too. No difference either.

Thanks for your patience

**Comment by jmarmstrong1207** [comment]
You can find it in the Admin settings, the bottom of that page.
![Screenshot 2024-07-25 at 10 40 16 AM](https://github.com/user-attachments/assets/9914c035-7850-4447-a3a9-484b38dee486)

**Comment by Creepo** [comment]
[calibre-web (1).log](https://github.com/user-attachments/files/16381847/calibre-web.1.log)

Here you go.

**Comment by jmarmstrong1207** [comment]
Looks like a 503 server error from Amazon. I found a similar issue in calibre-web janeczku/calibre-web#2719. Looks like Amazon blocks requests if it gets spammed too much. This is probably the culprit

**Comment by flintstones-fred** [comment]
I am having the same issue. I followed through the steps suggested by @crocodilestick  and then by @jmarmstrong1207 , however, still not able to get the new cover when I fetch metadata. I can see that the metadata.opf file does get updated which makes me think that the user is able to write to the directory. But the cover never gets updated. And if a cover never existed, then it doesn't bring a new cover selected from the "Fetch Metadata" page selection.

**Comment by crocodilestick** [comment]
@flintstones-fred you have Uploads disabled. Go to Settings -> Basic Configuration -> Feature Configuration -> Enable Uploads

**Comment by flintstones-fred** [comment]
> @flintstones-fred you have Uploads disabled. Go to Settings -> Basic Configuration -> Feature Configuration -> Enable Uploads 

Thank you! It works as intended now!
