### ISSUE TITLE
Add notification when there is a new update

### ISSUE THREAD

**Issue by jmarmstrong1207** [crocodilestick/Calibre-Web-Automator#19]
For user friendliness, there should be notification when there is a new update available for the container.

This will be implemented via a script that checks once per day, then shows the notification with the info. Must find out how notifications are implemented, but it looks like the script has to be native within calibre-web's web server

**Comment by TheDMV2** [comment]
Notification by email to admin account, and/or by text/graphic in the web UI to certain accounts when they're logged in? I wouldn't want an update notification to show for all my users.

**Comment by crocodilestick** [comment]
Feature added in V1.3.0 due to release soon. @TheDMV2, the feature is admin only yes
