### ISSUE TITLE
Downloading torrent files direct into cwa-ingest causes errors and duplicate imports

### ISSUE THREAD

**Issue by jmarmstrong1207** [crocodilestick/Calibre-Web-Automator#28]
I am speculating its due to how torrent downloading works, where it downloads in chunks, so sometimes it partially downloads a file then triggers close_write after that chunk is done, then proceeds to another file. inotifywait is likely seeing that close_write and triggers the import process.

For now, the fix will be to make a warning in the readme to NOT download torrents directly inside cwa-book-ingest

**Comment by TheDMV2** [comment]
Are you putting partially completed files into the ingest folder? That seems like a Bad Idea[tm].

You should have a partially completed folder, and a finished folder; and that second folder could be watched by the ingester, but I wouldn't ever have anything touch an active download.

**Comment by jmarmstrong1207** [comment]
> Are you putting partially completed files into the ingest folder? That seems like a Bad Idea[tm].
> 
> You should have a partially completed folder, and a finished folder; and that second folder could be watched by the ingester, but I wouldn't ever have anything touch an active download.

True. Make a warning in readme to not download directly in it
