### ISSUE TITLE
Update docker image to 0.6.2.2

### ISSUE THREAD

**Issue by jmarmstrong1207** [crocodilestick/Calibre-Web-Automator#3]
Not sure how exactly the docker image is built, but it seems that it's build on top of Calibre-web's docker image. Am I correct? If so, there's a new update and the image looks like it needs to reference 0.6.2.2 to be the latest version.

I love this project btw! This is what I've been looking for

**Comment by crocodilestick** [comment]
Hey James, that's correct it is. I have a snapshot of the Calibre-Web image it was built upon also on DockerHub for dev work ect at crocodilestick/calibre-web-base with the base Docker Compose template used too.
