### ISSUE TITLE
[Feature Request] Add "Auto" to name/logo in the top left corner

### ISSUE THREAD

**Issue by TheDMV2** [crocodilestick/Calibre-Web-Automator#39]
No reason not to properly identify this project! :-)

Here's a snippet of HTML/CSS for you!

<img width="217" alt="Screenshot" src="https://github.com/user-attachments/assets/af04f5a9-16f0-46da-a565-95c3fd0241e2">

```
<a class="navbar-brand" href="/">Calibre-Web<span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; writing-mode: vertical-rl; text-orientation: upright;font-size: 0.24em; letter-spacing: -3px;vertical-align: bottom;">AUTO</span></a>
```

Also, on the "About" page, shouldn't it be "Calibre-Web Automated ?

<img width="483" alt="Screenshot" src="https://github.com/user-attachments/assets/31d38f60-208a-49f8-993e-f5bc0f2ef3f2">

And shouldn't the first version item be CWA?

**Comment by crocodilestick** [comment]
Hey @TheDMV2 that's sick! Are they just mock-ups or have you already prepared modded files?

**Comment by TheDMV2** [comment]
Neither; that was just temporarily edited HTML in my browser console. Wasn't even saved, except for the copy/paste I gave you above.

**Comment by crocodilestick** [comment]
@TheDMV2 , thanks for the suggestion, it's been added to V1.3.0 which will release soon

**Comment by iroQuai** [comment]
I tried changing the title (into "my books" instead of calibre-web, as I always do) but those changes do not register. 

The text area also said "calibre-web" instead of the full current title (with automated included)

Wouldn't that be the best way of changing the title?

**Comment by iroQuai** [comment]
@crocodilestick  this is marked as closed but not implemented, right? 
The title option in UI Config doens't function at all.

**Comment by TheDMV2** [comment]
> @crocodilestick this is marked as closed but not implemented, right? The title option in UI Config doens't function at all.

This has already been reported in issue #52 

And this UI change could be done in custom CSS, which I've requested in issue #53
