### ISSUE TITLE
Docker compose wont build if optional gmail.json is not mounted

### ISSUE THREAD

**Issue by jmarmstrong1207** [crocodilestick/Calibre-Web-Automator#4]
Docker compose will not build if I remove `- /path/to/your/gmail/credentials.json:/app/calibre-web/gmail.json #Optional` from the docker compose. 

This is the error:
`Error response from daemon: cannot mount volume over existing file, file exists /var/lib/docker/overlay2/5682e9dc0a0c5134f989edbd99176a31d04fa033df8a18a0a9d10433731d177b/merged/app/calibre-web/gmail.json
`

I was able to fix it by adding the bind mount for gmail.json back in

**Comment by crocodilestick** [comment]
Weird, I'll definitely look into that

**Comment by crocodilestick** [comment]
Hi James, just fixed the issue, /books was also unintentionally required, just pushed a new image to Docker Hub with the fixes, re-pull the image and I'll mark this issue as closed 👍
