### ISSUE TITLE
Add an empty metadata.db to repo to make installation process easier

### ISSUE THREAD

**Issue by jmarmstrong1207** [crocodilestick/Calibre-Web-Automator#5]
Sorry for the spam issues, but I'm just putting out quick posts for potential improvements that I see!
 
Current README references an article for creating a metadata.db file via entering the docker container and using commands. We can streamline this process by adding an empty metadata.db file to the repo and updating the README to instruct users to download it and make calibre-web-automator use it. This is the same as how calibre-web's README is currently

[Calibre-web's metadata.db](https://github.com/janeczku/calibre-web/blob/master/library/metadata.db)
[Calibre-web README reference (Quick start, step 3)](https://github.com/janeczku/calibre-web?tab=readme-ov-file#quick-start )

**Comment by crocodilestick** [comment]
Hey James, don't be silly your suggestions have all been super helpful! Added a metadata.db file as suggested and updated the README accordingly 👍
