### ISSUE TITLE
cwa automator creates a brand new metadata.db instead of the one in /calibre-main/

### ISSUE THREAD

**Issue by jmarmstrong1207** [crocodilestick/Calibre-Web-Automator#6]
Following the instructions in the README placing an empty metadata.db file in `/calibre-main/` (Directory within container), adding books to cwa-book-ingest works perfectly, but instead of putting the books in `/calibre-main/metadata.db`, it creates a brand new directory, creates a new db, resulting in `/calibre-main/Calibre Library/metadata.db`. Switching the database to this newly-created one shows the imported books.

my compose file for reference:
```services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=100
      - TZ=UTC
    volumes:
      - ./config:/config
      - ./cwa-book-ingest:/cwa-book-ingest
      - ./library:/calibre-main
      - ./books:/books #Optional
      - ./credentials.json:/app/calibre-web/gmail.json #Optional

    ports:
      - 8083:8083 # Change the first number to change the port you want to access the Web UI, not the second
    restart: unless-stopped
```

**Comment by crocodilestick** [comment]
Hi James, it sounds like you bound the wrong folder to the '/calibre-main' folder. It shouldn't be bound the the 'Calibre Library' folder directly, it should be bound to the folder that contains that folder with your 'metadata.db' in it, that's what I meant by binding it to the config folder of your Calibre instance in the README. Let me know if that fixes it!

**Comment by jmarmstrong1207** [comment]
I've done that. The directory I mounted only includes metadata.db and nothing else, but it creates a "Calibre Library" folder with another metadata.db file in "Calibre Library". Maybe it's a edge case if the user doesn't create or have a "Calibre Library" folder?

**Comment by jmarmstrong1207** [comment]
[I might have found the culprit. ](https://github.com/crocodilestick/Calibre-Web-Automator/blob/03d8c6664cd1c93fdeb1919b13d5f3546ea13fd1/calibre-web-automator/new-book-detector.sh#L22). Line 22 for that file is using $CALIBRE_LIBRARY, but in the container that var is set to "/calibre-main/Calibre LIbrary"`.  I manually executed line 22 and it indeed creates a new library in `/calibre-main/Calibre Library` and creates a brand new metadata.db file here. _(Given that I discovered this, we might be able to automate the installation process so the user does not have to manually add an empty metadata.db file)_

I seem to fix this by Manually executing `calibredb add` so that the library path is instead`/calibre-main/`,  and it seems to work, adding the book directly to the existing metadata.db file in `/calibre-main/metadata.db`

**Comment by jmarmstrong1207** [comment]
Actually, I see what you mean! the empty metadata.db should be in `/calibre-main/Calibre Library/metadata.db`. README isn't clear, so I'll make a PR for it

**Comment by jmarmstrong1207** [comment]
We can also make the script automatically add an empty metadata.db file to /calibre-main/Calibre Library somehow

**Comment by crocodilestick** [comment]
Hey James, thanks for being so active on the project! For some reason I thought the metadata.db file resided on the same level as the 'Calibre Library' folder and not within it but after just checking yeah you're 100% right. I'll make sure your push request changing the bind wouldn't break anything and get back to you.

As to a script to make one for new users yeah that should be easy enough to do, we can make a one-time run s6-rc.d process that can check if the 'Calibre Library' folder exists in the bind and there's a valid metadata.db file in it during container start up then create them if not, I'll get on that.

**Comment by crocodilestick** [comment]
Fixed with most recent merge
